.PHONY: clean All

All:
	@echo "----------Building project:[ EX16 - Debug ]----------"
	@cd "EX16" && "$(MAKE)" -f  "EX16.mk"
clean:
	@echo "----------Cleaning project:[ EX16 - Debug ]----------"
	@cd "EX16" && "$(MAKE)" -f  "EX16.mk" clean
